#!/bin/bash

# Cloudflare HTTPS Setup for admin.racetrackstreaming.com
# This script guides you through setting up Cloudflare for free HTTPS

set -e

DOMAIN="racetrackstreaming.com"
SUBDOMAIN="admin"
RECORD_NAME="${SUBDOMAIN}.${DOMAIN}"

echo "🔒 Cloudflare HTTPS Setup for ${RECORD_NAME}"
echo "=================================================="
echo ""
echo "This will configure Cloudflare to provide HTTPS for your admin dashboard."
echo ""

# Get ALB DNS name
ALB_DNS="broadcast-alb-525661146.us-east-1.elb.amazonaws.com"

echo "📋 STEP 1: Manual Setup in Cloudflare Dashboard"
echo "==============================================="
echo ""
echo "1. Log into Cloudflare: https://dash.cloudflare.com"
echo ""
echo "2. If you haven't added ${DOMAIN} yet:"
echo "   - Click 'Add a Site'"
echo "   - Enter: ${DOMAIN}"
echo "   - Select 'Free' plan"
echo "   - Complete Cloudflare onboarding"
echo ""
echo "3. Update nameservers in Route53 (AWS Console):"
echo "   - Go to Route53 hosted zones"
echo "   - Select: ${DOMAIN}"
echo "   - Note the current NS records (you can restore if needed)"
echo "   - Replace NS records with Cloudflare's nameservers"
echo "   - Cloudflare will show you the nameservers to use"
echo ""
echo "4. Add DNS Record in Cloudflare:"
echo "   - Go to: DNS → Records"
echo "   - Click 'Add record'"
echo "   - Type: A"
echo "   - Name: ${SUBDOMAIN}"
echo "   - IPv4: ${ALB_DNS}"
echo "   - Proxy status: Proxied (orange cloud) ⭐"
echo "   - TTL: Auto"
echo "   - Save"
echo ""
echo "5. Enable Flexible SSL:"
echo "   - Go to: SSL/TLS → Overview"
echo "   - Set mode to: 'Flexible' (not Full Strict)"
echo "   - This allows HTTPS browser → Cloudflare → HTTP ALB"
echo ""
echo "6. Optional - Enable HTTPS redirect:"
echo "   - Go to: Rules → Page Rules"
echo "   - Create rule: https://${RECORD_NAME}/*"
echo "   - Action: Always Use HTTPS"
echo ""

echo "⏳ STEP 2: Wait for DNS Propagation"
echo "===================================="
echo ""
echo "After updating nameservers in Route53, wait 5-15 minutes for:"
echo "  • New nameservers to propagate globally"
echo "  • Cloudflare to issue SSL certificate"
echo "  • DNS to resolve to Cloudflare's proxy"
echo ""

echo "✅ STEP 3: Verify Setup"
echo "======================="
echo ""
echo "Once DNS propagates, test with:"
echo ""
echo "  # Check DNS resolution (should show Cloudflare IPs)"
echo "  nslookup admin.racetrackstreaming.com"
echo ""
echo "  # Test HTTPS endpoint"
echo "  curl -I https://admin.racetrackstreaming.com/"
echo ""
echo "  # Check certificate issuer (should show Cloudflare/DigiCert)"
echo "  echo | openssl s_client -connect admin.racetrackstreaming.com:443 2>/dev/null | grep Issuer"
echo ""
echo "Expected response:"
echo "  • Status: 301 (Cloudflare forwards to HTTPS)"
echo "  • Certificate: DigiCert / Cloudflare"
echo "  • Browser: Green lock, no warnings"
echo ""

echo "📝 TROUBLESHOOTING"
echo "=================="
echo ""
echo "If HTTPS still doesn't work after 15 minutes:"
echo ""
echo "1. Verify nameservers updated:"
echo "   dig ${DOMAIN} NS +short"
echo ""
echo "2. Check Cloudflare DNS record:"
echo "   - Login to Cloudflare dashboard"
echo "   - Verify ${SUBDOMAIN} record points to ALB"
echo ""
echo "3. Verify ALB is responding:"
echo "   curl -v http://${ALB_DNS}/"
echo ""
echo "4. Check Cloudflare SSL status:"
echo "   - Go to SSL/TLS → Overview"
echo "   - Ensure set to 'Flexible'"
echo ""
echo "5. Clear DNS cache and retry:"
echo "   sudo dscacheutil -flushcache  # macOS"
echo "   ipconfig /flushdns             # Windows"
echo "   sudo systemctl restart systemd-resolved  # Linux"
echo ""

echo "🎉 Setup Complete!"
echo "After verification, your dashboard will be accessible at:"
echo "   https://admin.racetrackstreaming.com"
echo ""
